services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:

      - POSTGRES_DB=example
      - DB_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - spring-postgres
    depends_on:
      - db
    secrets:
      - db-password
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  db-data:
    driver: local
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:

